[package]
name = "rant"
version = "4.0.0-alpha-1"
authors = ["Nicholas Fleck <TheBerkin@users.noreply.github.com>"]
edition = "2018"
homepage = "https://berkin.me/rant"
repository = "https://github.com/TheBerkin/rant"
license = "MIT"
readme = "README.md"
#keywords = ["rant", "rantlang", "procedural", "text", "generation"]
#categories = ["text-processing", "game-development", "template-engine"]
description = "(Reserved for future use) The Rant procedural text generation language"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[[bin]]
name = "rant"
path = "src/tools/repl/main.rs"

[dependencies]
embedded-triple = "0.1.0"
logos = "0.11.4"
line-col = "0.1.1"