[package]
name = "rant"
version = "4.0.0-alpha.1"
authors = ["Nicholas Fleck <TheBerkin@users.noreply.github.com>"]
edition = "2018"
homepage = "https://rant-lang.org"
repository = "https://github.com/rant-lang/rant"
license = "MIT"
readme = "README.md"
keywords = ["rant", "rantlang", "procedural", "text", "generation"]
categories = ["text-processing", "game-development", "template-engine"]
description = "The Rant procedural text generation language"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[profile.release]
opt-level = 3
codegen-units = 1
lto = true

[[bin]]
name = "rant"
path = "src/tools/cli/main.rs"


[dependencies]
# Library
cast = "0.2.3"
fnv = "1.0.7"
line-col = "0.2.1"
logos = "0.11.4"
rand = "0.7.3"
rand_xoshiro = "0.4.0"
smartstring = "0.2.3"

# CLI
argh = "0.1.3"
codemap = "0.1.3"
codemap-diagnostic = "0.1.1"
colored = "2.0.0"
ctrlc = "3.1.6"
embedded-triple = "0.1.0"
exitcode = "1.1.2"